import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useLayoutEffect } from "react";
import { renderMetaTags } from "react-datocms";
import { ComponentLoader } from "core/ComponentLoader";
import { useStore } from "@lib/store";
import mappingNav from "@components/Global/GlobalNavigation/mapping";
import mappingFooter from "@components/Global/GlobalFooter/mapping";

export default function Layout({
  children,
  navigationData: cmsNavigationData,
  footerData: cmsFooterData,
  components,
  data,
  seo,
  siteSeo,
  context,
  preview,
}) {
  const router = useRouter();

  const pageUrl = `${process.env.NEXT_PUBLIC_SITE_URL}${
    router.asPath.split("?")[0]
  }`;

  const navigationData = useStore(({ navigationData }) => navigationData);
  const setNavigationData = useStore((state) => state.setNavigationData);
  const footerData = useStore(({ footerData }) => footerData);
  const setFooterData = useStore((state) => state.setFooterData);
  // const setPreview = useStore(({ setPreview }) => setPreview);

  useLayoutEffect(() => {
    window.scrollTo(0, 0);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!navigationData) {
      const mapped = mappingNav(cmsNavigationData);
      console.log("mapped", mapped);
      setNavigationData(mapped);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cmsNavigationData]);

  // useEffect(() => {
  //   if (!navigationData) {
  //     const mapped = mappingNav(cmsNavigationData);
  //     setNavigationData(mapped);
  //   }

  //   if (!formData && cmsNavigationData?.contactForm) {
  //     const formMapped = mappingForm(cmsNavigationData?.contactForm);
  //     setFormData(formMapped);
  //   }
  //   // eslint-disable-next-line react-hooks/exhaustive-deps
  // }, [cmsNavigationData]);

  useEffect(() => {
    if (!footerData) {
      const mapped = mappingFooter(cmsFooterData);
      setFooterData(mapped);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cmsFooterData]);

  // useEffect(() => {
  //   setPreview(preview);
  //   // eslint-disable-next-line react-hooks/exhaustive-deps
  // }, [preview]);
  // console.group();
  // console.log("Components", components);
  // console.log("Data", data);
  // // console.log("Children", children);
  // console.groupEnd();

  return (
    <>
      <Head>
        <title>Dato Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {seo && siteSeo && renderMetaTags([...seo, ...siteSeo.faviconMetaTags])}
        <link rel="icon" href="/favicon.svg" />
        {/* <link rel="canonical" href={canonicalUrl || pageUrl} /> */}
      </Head>
      {/* {children} */}

      <ComponentLoader
        models={data}
        components={components}
        context={{
          ...context, // If you have data that needs to be shared with all components, provide a value to the context prop. The prop will be passed to each component.
        }}
      />
      {children}
    </>
  );
}
